Idea.delete_all

# RFS
Idea.find_by(title: "Marketplace for buying and selling small businesses") || Idea.create(title: "Marketplace for buying and selling small businesses", content: "SMBs make up 99% of US businesses. Right now, the current buying and selling methods are broken — they occur primarily offline (newspaper ads, posters, word of mouth). There are a few online competitors (a signal of demand), but they are outdated. Lifestyle businesses are becoming more popular — a marketplace like this can facilitate financing and discovery to make owning one of these businesses possible.", source: "RFS 100 newsletter (Tina Jiang)", link: "https://rfs100.substack.com/p/avatars-chinese-e-commerce-and-tracking")

Idea.find_by(title: "Avatar for online shopping") || Idea.create(title: "Avatar for online shopping", content: "I often wish for something that would recommend clothes based on my body shape, then virtually show me how they'd look. On a personal level, it would drastically improve the online shopping experience. On a more global and environmental level, it would result in fewer returns and more efficient production as retailers are able to better forecast customer sizing.", source: "RFS 100 newsletter (Camilla Mazzolini)", link: "https://rfs100.substack.com/p/avatars-chinese-e-commerce-and-tracking")

Idea.find_by(title: "Pinduoduo for the US") || Idea.create(title: "Pinduoduo for the US", content: "Pinduoduo is a Chinese e-commerce platform with 'social buying' features that allow customers to team up, order in bulk, and receive discounts. We're continuing to see a shift from thinking about supply-first (how much can we produce) to demand-first (how much do we need to produce). Solutions like Pinduoduo can limit supply chain waste, give consumers lower prices, and flip the cost structures of incumbents on their heads. It's a win-win.", source: "RFS 100 newsletter (Turner Novak)", link: "https://rfs100.substack.com/p/avatars-chinese-e-commerce-and-tracking")

Idea.find_by(title: "Goodreads (but not bad)") || Idea.create(title: "Goodreads (but not bad)", content: "Amazon acquired Goodreads in 2007 and has sadly neglected it since. Instead of user-generated lists, a modern platform for book recommendations would use some sort of algorithm to make suggestions based on personal rankings and taste graphs. Bringing back social and community elements could also help people discover others with similar preferences.", source: "RFS 100 newsletter (Sam Huleatt)", link: "https://rfs100.substack.com/p/cameo-for-normal-people-segment-for")

Idea.find_by(title: "TikTok x WebMD for being an adult") || Idea.create(title: "TikTok x WebMD for being an adult", content: "Technology has meaningfully improved access to information but now, much of our day-to-day struggle as consumers is attributable to a lack of filtering ability. Because of this, I believe there is immense value in doing something very simple: getting the right information to the right person at the right time. I'd love to see a product that packages personal finance and 'adulting' content in a fun way that can become the pocket tool for the modern adult.", source: "RFS 100 newsletter (Chris Brown)", link: "https://rfs100.substack.com/p/cameo-for-normal-people-segment-for")

Idea.find_by(title: "Meme school") || Idea.create(title: "Meme school", content: "Why do we have to learn only from blobs of text and linear video? Memes are the internet's native vessel for ideas and shared experiences, and with so much learning now happening online, let's apply it to education! I'd love to see a marketplace for study material driven by original, nutritious memes.", source: "RFS 100 newsletter (Jonathan Libov)", link: "https://rfs100.substack.com/p/rfs-100-podcast-discovery-learning")

Idea.find_by(title: "Smart podcast search") || Idea.create(title: "Smart podcast search", content: "Most podcasts only have a title and brief description so unless we're already a listener, we have to go in blind. It’d be interesting if podcasts had automatically generated notes that could be annotated by listeners, searched for by prospective listeners, timestamped for playback, and so on.", source: "RFS 100 newsletter (Nandu Anilal)", link: "https://rfs100.substack.com/p/rfs-100-podcast-discovery-learning")

Idea.find_by(title: "Kickstarter for product features") || Idea.create(title: "Kickstarter for product features", content: "Although Kickstarter remains the obvious destination for new artistic projects, CPG brands, and some gadgetry, it's not built to drive software development. A platform for product teams to outline proposed features and solicit upfront subscriptions would provide hugely valuable market feedback, aligning companies with their customers.", source: "RFS 100 newsletter (Martin Strutz)", link: "https://rfs100.substack.com/p/were-on-product-hunt-plus-10-new")

Idea.find_by(title: "Cloud grocery stores") || Idea.create(title: "Cloud grocery stores", content: "Smaller, pickup-only grocery stores could offer a few advantages, particularly in metropolitan areas. They would reduce two of the biggest cost centers: headcount and footprint. Customers could place orders ahead of time and have their orders ready to go when they arrived. In turn, stores could use those phone numbers to share special offers or other incentives.", source: "RFS 100 newsletter (Molly O'Shea)", link: "https://rfs100.substack.com/p/the-unbundled-mba-rakuten-for-humans")

Idea.find_by(title: "Headspace for hypnosis") || Idea.create(title: "Headspace for hypnosis", content: "Mental healthcare is the #1 public health crisis in America. Today, 38M Americans are on antidepressants, while 20M Americans are on anti-anxiety medication. Research shows strong evidence that hypnotherapy can effectively address insomnia and PTSD, with potential to treat depression, anxiety, and more. What meditation is today, hypnotherapy might be tomorrow.", source: "RFS 100 newsletter (Meera Clark)", link: "https://rfs100.substack.com/p/rfs-100-talking-to-animals-with-machine")

Idea.find_by(title: "Personal advisory board for wellness") || Idea.create(title: "Personal advisory board for wellness", content: "A company could bundle access to an 'advisory board' of personal coaches, counselors, and educators, pairing expertise with tools that allow practitioners to scale. Such a solution could significantly bend the cost curve of access down while helping tens of thousands of practitioners build thriving small businesses.", source: "RFS 100 newsletter (Brett Bivens)", link: "https://rfs100.substack.com/p/rfs-100-talking-to-animals-with-machine")

Idea.find_by(title: "Social network for floraphiles") || Idea.create(title: "Social network for floraphiles", content: "A Statista global survey found that 25% of US respondents consider gardening a hobby, placing it above 'playing sports' and 'photography'. r/gardening has over 3M members and comments per day have increased over the past year. A community for plant parents could flower into a platform unto itself, with little competition to worry about.", source: "RFS 100 newsletter (Mario Gabriele)", link: "https://rfs100.substack.com/p/toilet-tech-resurrecting-myspace")

Idea.find_by(title: "Influencer-led learning") || Idea.create(title: "Influencer-led learning", content: "To create engaging educational content, you could pair subject matter experts with Instagram and TikTok stars that appeal to younger audiences. The experts would craft lesson plans and celebrities would teach them. A content portal to discover and pursue their academic interests could help nurture a child's love for learning.", source: "RFS 100 newsletter (Nick DeWilde)", link: "https://rfs100.substack.com/p/toilet-tech-resurrecting-myspace")

Idea.find_by(title: "Figma for video") || Idea.create(title: "Figma for video", content: "Video provides higher content density than almost any other medium and yet, professional-grade editing software lacks real-time, collaborative functionality. Often stored locally, film repositories also tend to lack the intuitive search and tagging features necessary for a team-based product. There's an opportunity to transport all of this into a web-based platform.", source: "RFS 100 newsletter (Hannah Murdoch)", link: "https://rfs100.substack.com/p/social-avatars-trustpilot-for-1099s")

Idea.find_by(title: "Trustpilot for gig and hourly workers") || Idea.create(title: "Trustpilot for gig and hourly workers", content: "The difference between a 4 and 5-star Uber ride may be a function of the rider’s mood; for the driver it's a matter of survival. A third-party platform where employees collect, curate, and showcase their professional data would help gig workers and potential employers alike. Reducing information asymmetry in the hiring process is mutually beneficial.", source: "RFS 100 newsletter (Brett Martin)", link: "https://rfs100.substack.com/p/social-avatars-trustpilot-for-1099s")


# MFM
Idea.find_by(title: "Modern perks for remote-first teams") || Idea.create(title: "Modern perks for remote-first teams", content: "The best company perks abstract away the worst parts of an employee's job. Large organizations have long counted on these to attract top talent but with much of the world working from home, there's ample opportunity to rethink benefits. Free books, mental health support services, and Upwork stipends for menial tasks are just a few examples.", source: "My First Million podcast (Steph Smith)", link: "https://open.spotify.com/episode/2riDxsu51lCPFUTO5WEgtG?si=yiPf_q8IQXOriTpQwpXGFg")

Idea.find_by(title: "Dev shop for celebrities") || Idea.create(title: "Dev shop for celebrities", content: "Most celebrity websites are painfully bad and narrowly focused on selling merch. Fan sites aggregating relevant news about stars and their posts on social media could easily rank well on SEO. Even just a simple landing page with an email capture form would be useful. These could be sold back to the celebs or if they're not interested, serve as standalone businesses using affiliate links.", source: "My First Million podcast (Steph Smith)", link: "https://open.spotify.com/episode/2riDxsu51lCPFUTO5WEgtG?si=yiPf_q8IQXOriTpQwpXGFg")

Idea.find_by(title: "Fantasy investing") || Idea.create(title: "Fantasy investing", content: "Combine the best of sports betting, fantasy sports, and public trading. Instead of wasting real money on Robinhood, users would get a designated amount of fake money to put down on individual stocks and compete for the best returns over a week, month, or year. Prizes for top performers could be financed with ad revenue.", source: "My First Million podcast (Elaine Zelby)", link: "https://open.spotify.com/episode/7nEm14ZQhC9jZfVAikjezY?si=TVzMsongTJCSGvOMCRAwOg")

Idea.find_by(title: "Life schools") || Idea.create(title: "Life schools", content: "There should be online courses for every important, but overlooked aspect of adulthood. Think content around personal finance, parenting, mortgages, and more. The internet is awesome for learning about relatively simple things, but most people would probably prefer divorce guidance from an expert rather than a random YouTuber.", source: "My First Million podcast (Shaan Puri)", link: "https://open.spotify.com/episode/3FptHYMK6TpsBPbpvr6Xjt?si=_Hk7YAdlQ-qT2KnvKARbmg")

Idea.find_by(title: "Authentic dating app") || Idea.create(title: "Authentic dating app", content: "You open up the app on your phone and there's no profiles or text. In order to use it, you have to record an answer to a randomly selected question and then you can browse responses from other people. This type of video dating app would reveal much more personality than a traditional, highly curated profile.", source: "My First Million podcast (Anthony Pompliano)", link: "https://open.spotify.com/episode/4F90EWkRyMjjKfjRKkLvZR?si=iQ5V_bEwS4G319VRbEWc3A")

Idea.find_by(title: "XPRIZE for large companies") || Idea.create(title: "XPRIZE for large companies", content: "XPrize puts up large cash prizes for the best solutions to big, hairy problems. Instead of dedicating resources indefinitely, enterprises could offer XPRIZE-esque bounties -- a fixed amount -- for anyone outside of the organization to help them overcome a daunting internal obstacle. More shots on goal tends to offer a greater likelihood of scoring.", source: "My First Million podcast (Shaan Puri)", link: "https://open.spotify.com/episode/0KzKdYdWP55vtcR8Wv2Zzx?si=_D6KLRGaRlOQvUH7hsaNcg")


# Twitter
# Idea.find_by(title: "") || Idea.create(title: "", content: "", source: "", link: "")

Idea.find_by(title: "Strava for cooking") || Idea.create(title: "Strava for cooking", content: "Strava is a social network for serious-yet-amateur athletes. I believe there’s an opportunity for a vertical social network built for serious-yet-amateur home cooks. Similar to Strava, you’d start by offering single-player tools. For Strava that’s been route planning and segments; for cooking that might be a database of web-crawled recipes with a Gantt chart interface to manage the timing of a multi-course meal. As a user base develops, you’d start adding in multiplayer social features.", source: "Twitter thread (Dan Romero)", link: "https://twitter.com/dwr/status/1330170952932536321?s=20")

Idea.find_by(title: "Startup incubator with income pooling") || Idea.create(title: "Startup incubator with income pooling", content: "Request for incubator: startup founders gain equity in batch-mates' companies. The batch is even more incentivized to work together, resulting in better returns, and risk is smoothed across everyone in the cohort.", source: "Twitter thread (Helena Merk)", link: "https://twitter.com/HelenaMerk/status/1278123506614407168?s=20")

Idea.find_by(title: "Incentivizing matchmaking") || Idea.create(title: "Incentivizing matchmaking", content: "Request for product: I want to match make my friends. I want an app that creates a seamless experience for my friends to swipe right on each other and to get credit for connecting them. I know lots of people who also want to do this for their friends.", source: "Twitter thread (Erik Torenberg)", link: "https://twitter.com/eriktorenberg/status/1214987621681680385?s=20")

Idea.find_by(title: "Media brand for Arab Americans") || Idea.create(title: "Media brand for Arab Americans", content: "There are 3.7M Arab Americans in the US, up from 1.7M in 2010. Dubai-based Noor Naim recently became the first Arab YouTuber to hit 10M subscribers and a number of Arab American influencers, like Issa Tweimeh, have been gaining traction. A modern entertainment and podcast network for and by the youth would be interesting.", source: "Twitter thread (Aaron McClendon)", link: "https://twitter.com/faintflex/status/1120356960715595777?s=20")

Idea.find_by(title: "Source of truth for user-facing copy") || Idea.create(title: "Source of truth for user-facing copy", content: "A GitHub add-on that makes it easy to see all user-facing copy across an entire repo would be super useful. Error messages, menus, tooltips, mailers, dynamic copy/pages, and regular website copy... all in one place.", source: "Twitter thread (Austin Smith)", link: "https://twitter.com/awwstn/status/1262457476873478148?s=20")
